title: Erina Nur Susilowati # your name (or website title) here
logo: "/images/profil.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Peserta PZSIB Data Warehousing, Analysis, and Visualization for Business Insight
  Universitas Pendidikan Indonesia
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/erina-nur-susilowati-399377214">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

